title: Ty's Homepage
page-top-title: Tao Ye 
top-section-bg-text: Shanghai Jiao Tong University
home-subtitle: Yourname&ensp;|&ensp;Yezige
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
